/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            "colors": {
                "on-error": "var(--color-on-error)",
                "outline-variant": "var(--color-outline-variant)",
                "on-error-container": "var(--color-on-error-container)",
                "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
                "surface-container-high": "var(--color-surface-container-high)",
                "on-primary": "var(--color-on-primary)",
                "surface-container-low": "var(--color-surface-container-low)",
                "tertiary-fixed": "var(--color-tertiary-fixed)",
                "error-container": "var(--color-error-container)",
                "error": "var(--color-error)",
                "on-surface": "var(--color-on-surface)",
                "surface-bright": "var(--color-surface-bright)",
                "on-tertiary-container": "var(--color-on-tertiary-container)",
                "secondary-container": "var(--color-secondary-container)",
                "primary-fixed-dim": "var(--color-primary-fixed-dim)",
                "surface-container-highest": "var(--color-surface-container-highest)",
                "on-background": "var(--color-on-background)",
                "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
                "surface-dim": "var(--color-surface-dim)",
                "primary-container": "var(--color-primary-container)",
                "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
                "on-secondary-container": "var(--color-on-secondary-container)",
                "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
                "tertiary": "var(--color-tertiary)",
                "outline": "var(--color-outline)",
                "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
                "on-surface-variant": "var(--color-on-surface-variant)",
                "secondary-fixed": "var(--color-secondary-fixed)",
                "secondary": "var(--color-secondary)",
                "on-secondary": "var(--color-on-secondary)",
                "inverse-surface": "var(--color-inverse-surface)",
                "background": "var(--color-background)",
                "primary": "var(--color-primary)",
                "surface-container": "var(--color-surface-container)",
                "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
                "on-primary-fixed": "var(--color-on-primary-fixed)",
                "on-secondary-fixed": "var(--color-on-secondary-fixed)",
                "surface-variant": "var(--color-surface-variant)",
                "surface-tint": "var(--color-surface-tint)",
                "surface-container-lowest": "var(--color-surface-container-lowest)",
                "primary-fixed": "var(--color-primary-fixed)",
                "inverse-on-surface": "var(--color-inverse-on-surface)",
                "surface": "var(--color-surface)",
                "tertiary-container": "var(--color-tertiary-container)",
                "on-primary-container": "var(--color-on-primary-container)",
                "on-tertiary": "var(--color-on-tertiary)",
                "inverse-primary": "var(--color-inverse-primary)"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "stack-xl": "120px",
                "stack-md": "24px",
                "stack-sm": "8px",
                "container-max": "1280px",
                "stack-lg": "64px",
                "margin-mobile": "20px",
                "gutter": "24px"
            },
            "fontFamily": {
                "headline-md": ["Space Grotesk"],
                "label-caps": ["Geist"],
                "body-sm": ["Inter"],
                "display-lg": ["Space Grotesk"],
                "body-lg": ["Inter"],
                "mono-code": ["Geist"],
                "display-lg-mobile": ["Space Grotesk"]
            },
            "fontSize": {
                "headline-md": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
                "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
                "display-lg": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                "mono-code": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "display-lg-mobile": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
        },
    },
    plugins: [],
}
